# Generated by Django 6.0.6 on 2026-06-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_id', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipos', models.CharField(max_length=200)),
                ('altura', models.IntegerField()),
                ('peso', models.IntegerField()),
            ],
        ),
    ]
